### ISSUE TITLE
Version number probably has to be updated

### ISSUE THREAD

**Issue by anvlkv** [fermyon/leptos-spin#34]
When using the template it comes with `spin-sdk` 2, when updating to 3 in my direct dependencies cargo would still install the 2.2 for `leptos-spin` and then complain about `spin-sdk` types from this crate and sdk not matching.

**Comment by itowlson** [comment]
You should now be able to update the leptos-spin reference to 0.2.0 and it will work with Spin SDK 3.  Sorry for the inconvenience and thanks for flagging this!

**Comment by itowlson** [comment]
Ugh, no, something is mad in wasm-bindgen.

**Comment by anvlkv** [comment]
I just saw your release and tried it, but I'm getting this error

```
rust-lld: error: duplicate symbol: spin-sdk-commit-unknown
          >>> defined in /Users/anvlkv/Projects/a-nvlkv-xyz/target/wasm32-wasi/release/deps/libspin_sdk-109f97ab378a0e65.rlib(spin_sdk-109f97ab378a0e65.spin_sdk.c36fca70ce385174-cgu.10.rcgu.o)
          >>> defined in /Users/anvlkv/Projects/a-nvlkv-xyz/target/wasm32-wasi/release/deps/libspin_sdk-05724204a9cc67bc.rlib(spin_sdk-05724204a9cc67bc.spin_sdk.f46661640224f52c-cgu.11.rcgu.o)

          rust-lld: error: duplicate symbol: spin-sdk-language-rust
          >>> defined in /Users/anvlkv/Projects/a-nvlkv-xyz/target/wasm32-wasi/release/deps/libspin_sdk-109f97ab378a0e65.rlib(spin_sdk-109f97ab378a0e65.spin_sdk.c36fca70ce385174-cgu.10.rcgu.o)
          >>> defined in /Users/anvlkv/Projects/a-nvlkv-xyz/target/wasm32-wasi/release/deps/libspin_sdk-05724204a9cc67bc.rlib(spin_sdk-05724204a9cc67bc.spin_sdk.f46661640224f52c-cgu.11.rcgu.o)

          rust-lld: error: duplicate symbol: cabi_realloc
          >>> defined in /Users/anvlkv/Projects/a-nvlkv-xyz/target/wasm32-wasi/release/deps/libwit_bindgen-892de5ba1845c8f7.rlib(wit_bindgen-892de5ba1845c8f7.wit_bindgen.286ad71f93492f62-cgu.0.rcgu.o)
          >>> defined in /Users/anvlkv/Projects/a-nvlkv-xyz/target/wasm32-wasi/release/deps/libwit_bindgen-e5dbfbf1e6383085.rlib(wit_bindgen-e5dbfbf1e6383085.wit_bindgen.743272be3208aa3e-cgu.0.rcgu.o)
```

**Comment by itowlson** [comment]
It looks like `leptos` itself links to `leptos-spin-macro` 0.1 which was linked to Spin SDK 2.2.  `leptos-spin-macro` 0.2 removes the Spin SDK dependency but we'll need to update the reference in `leptos` itself before we can fix this.  Sorry.  Can you continue on SDK 2.2 for now or is this a blocker for you?

**Comment by anvlkv** [comment]
No problem! All works on 2.2 and I will look forward to your next release
